# The Dockerimage-Tags, which should be deployed

ecotoxfred:
  image:
    repository: registry.hzdr.de/ufz/tb3-cite/cbc/ecotoxfred
    tag: "2026.0.1"

neo4j:
  image:
    repository: registry.hzdr.de/ufz/tb3-cite/cbc/ecotoxfred/neo4j-cheos:2026.0.0 
    tag: "2026.0.0"
